package main

import "testing"

// TestTerrainVariety samples a wide area and checks the generator produces the
// full range of landforms the feature is about: low sandy flats, ordinary
// grassland, bare mountain rock and snow-capped peaks, with a broad spread of
// heights.
func TestTerrainVariety(t *testing.T) {
	const span = 1200 // world units sampled per axis
	kinds := map[int]int{}
	minH, maxH := 1<<30, -1
	for x := -span; x < span; x += 3 {
		for z := -span; z < span; z += 3 {
			h := terrainHeight(x, z)
			if h < minH {
				minH = h
			}
			if h > maxH {
				maxH = h
			}
			surf, _ := surfaceBlocks(x, z, h)
			kinds[surf]++
		}
	}
	t.Logf("height range %d..%d; surfaces sand=%d grass=%d stone=%d snow=%d",
		minH, maxH, kinds[genSand], kinds[genGrass], kinds[genStone], kinds[genSnow])

	for _, k := range []struct {
		name string
		tp   int
	}{{"sand", genSand}, {"grass", genGrass}, {"stone", genStone}, {"snow", genSnow}} {
		if kinds[k.tp] == 0 {
			t.Errorf("no %s surfaces generated in sampled area", k.name)
		}
	}
	if maxH < genSnowLine {
		t.Errorf("tallest terrain %d never reached the snow line %d", maxH, genSnowLine)
	}
	if minH > genBeachTop {
		t.Errorf("lowest terrain %d never reached beach level %d", minH, genBeachTop)
	}
}

// TestCaveCarving checks caves hollow out a meaningful but not overwhelming
// fraction of the underground, and never breach the solid floor.
func TestCaveCarving(t *testing.T) {
	var solid, carved int
	for x := 0; x < 200; x++ {
		for z := 0; z < 200; z++ {
			h := terrainHeight(x, z)
			for y := 1; y < h; y++ {
				solid++
				if caveCarved(x, y, z) {
					carved++
				}
				if y < genCaveFloor && caveCarved(x, y, z) {
					t.Fatalf("cave carved below floor at (%d,%d,%d)", x, y, z)
				}
			}
		}
	}
	frac := float64(carved) / float64(solid)
	t.Logf("caves carved %.1f%% of underground (%d/%d)", frac*100, carved, solid)
	if frac < 0.02 || frac > 0.35 {
		t.Errorf("cave fraction %.3f out of expected 0.02..0.35 band", frac)
	}
}

// TestForestsAreDenserThanPlains confirms forest regions grow far more trees per
// unit area than sparse regions, so "forest" reads as a real biome.
func TestForestsAreDenserThanPlains(t *testing.T) {
	// Find the densest and sparsest 160x160 blocks in a large scan.
	best, worst := -1, 1<<30
	countTrees := func(ox, oz int) int {
		n := 0
		for cx := ox; cx < ox+32; cx++ {
			for cz := oz; cz < oz+32; cz++ {
				if _, ok := treeInCell(cx, cz); ok {
					n++
				}
			}
		}
		return n
	}
	for ox := -200; ox < 200; ox += 32 {
		for oz := -200; oz < 200; oz += 32 {
			n := countTrees(ox, oz)
			if n > best {
				best = n
			}
			if n < worst {
				worst = n
			}
		}
	}
	t.Logf("trees per 160x160 region: densest=%d sparsest=%d", best, worst)
	if best <= worst*2 {
		t.Errorf("forests not appreciably denser than plains: densest=%d sparsest=%d", best, worst)
	}
}

// TestTreesSpanChunkBorders verifies a tree whose canopy straddles a chunk seam
// is reproduced identically from either side, so generating the two chunks
// independently yields a seamless tree (no half-canopies at seams).
func TestTreesSpanChunkBorders(t *testing.T) {
	// Find a tree whose canopy actually crosses a chunk seam in X, then confirm
	// each of its blocks is generated by whichever chunk owns that block's
	// column -- so the whole tree survives being split across chunk boundaries.
	var straddler tree
	var expected map[Vec3]int
	found := false
	for cx := 0; cx < 400 && !found; cx++ {
		for cz := 0; cz < 400; cz++ {
			tr, ok := treeInCell(cx, cz)
			if !ok {
				continue
			}
			b := tr.blocks()
			lo, hi := 1<<30, -1<<30
			for p := range b {
				c := p.Chunkid().X
				if c < lo {
					lo = c
				}
				if c > hi {
					hi = c
				}
			}
			if lo != hi { // spans at least two chunks in X
				straddler, expected, found = tr, b, true
				break
			}
		}
	}
	if !found {
		t.Fatal("no seam-straddling tree found to test cross-chunk stitching")
	}
	t.Logf("straddling tree at (%d,%d) with %d blocks across chunks", straddler.x, straddler.z, len(expected))

	// Generate every chunk the tree touches and gather what they placed.
	got := map[Vec3]int{}
	seen := map[Vec3]bool{}
	for p := range expected {
		cid := p.Chunkid()
		if seen[cid] {
			continue
		}
		seen[cid] = true
		for bp, tp := range makeChunkMap(cid) {
			if tp == genWood || tp == genLeaves {
				got[bp] = tp
			}
		}
	}
	for p, tp := range expected {
		if got[p] != tp {
			t.Errorf("tree block %v: expected %d, chunk generation produced %d", p, tp, got[p])
		}
	}
}

// TestGeneratedBlocksStayInChunk guards the invariant chunk.add relies on: every
// block makeChunkMap emits must belong to the chunk it is generating.
func TestGeneratedBlocksStayInChunk(t *testing.T) {
	for _, cid := range []Vec3{{0, 0, 0}, {1, 0, 0}, {-1, 0, -1}, {5, 0, -3}} {
		m := makeChunkMap(cid)
		for p := range m {
			if p.Chunkid() != cid {
				t.Fatalf("chunk %v generated foreign block %v (chunk %v)", cid, p, p.Chunkid())
			}
			if p.Y < 0 || p.Y >= WorldHeight {
				t.Fatalf("chunk %v generated out-of-range block %v", cid, p)
			}
		}
	}
}
